# Generated by Django 5.0.4 on 2024-04-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chats',
            table='chat_tbl_chat',
        ),
    ]
