# Generated by Django 5.0.4 on 2024-04-23 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='Invalid First Name', regex='^[A-Za-z]{2,20}$')])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_last_name', message='Invalid Last Name', regex='^[A-Za-z\\-]{2,20}$')])),
                ('email', models.EmailField(error_messages={'unique': 'Email already exists.'}, max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
