# Generated by Django 5.0.4 on 2024-04-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbluser',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='tbluser',
            table='chat_tbl_user',
        ),
    ]
