# Generated by Django 5.0.4 on 2024-04-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_tbluser_options_alter_tbluser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
