# Generated by Django 5.0.4 on 2024-04-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_tbluser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
